main: PlateLauncher
name: PlateLauncher
version: 1.3.1
author: Darkm4tter
description: A simple plugin that allows players to launch themselves with pressure plates set in the world.
website: www.protocolmc.com
permissions:
  platelauncher.admin:
    description: Access to plate toggle command
    default: op
  platelauncher.launch:
    description: Access to plate launch command
    default: op
commands:
  plate:
    description: Toggle plate setting mode
    permission: platelauncher.admin
    aliases: [platelauncher, launcher]
    usage: /plate [command name]